using System;

public class LogEntry
{
    public long LogID { get; set; } // Assuming this is generated by the database
    public string UserHash { get; set; }
    public string ActionType { get; set; }
    public DateTime LogTime { get; set; }
    public string LogStatus { get; set; }
    public string LogDetail { get; set; }

    public LogEntry(string userHash, string actionType, string logStatus, string logDetail)
    {
        LogTime = DateTime.UtcNow;
        UserHash = userHash;
        ActionType = actionType;
        LogStatus = logStatus;
        LogDetail = logDetail;
    }
}